version: 2

updates:

  - package-ecosystem: github-actions
    directory: "/"
    open-pull-requests-limit: 99
    schedule:
      interval: daily
      time: "04:00"

  - package-ecosystem: maven
    directory: "/"
    open-pull-requests-limit: 99
    schedule:
      interval: daily
      time: "04:00"
