name: Build Dependabot

on:
  pull_request_target

jobs:
  build:
    name: Build
    if: ${{ github.actor == 'dependabot[bot]' }}
    uses: ./.github/workflows/reusable-build.yml
    with:
      sonar_analysis: false
      ref: ${{ github.event.pull_request.head.sha }}
