name: Publish Release Manual

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Specified version to publish'
        required: true

jobs:
  publish-manual:
    name: Manual Publish
    uses: ./.github/workflows/reusable-publish.yml
    with:
      version: ${{ inputs.version }}
