name: Publish Release

on:
  push:
    tags:
      - '**'

jobs:
  publish:
    name: Publish
    uses: fonimus/ssh-shell-spring-boot/.github/workflows/reusable-publish.yml@main
    with:
      version: ${{ github.ref }}
