name: Publish Release

on:
  push:
    tags:
      - '**'

jobs:
  release:
    name: Publish ${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v1.0.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Is Pre Release ?
        id: pre-release
        shell: bash
        run: |
          export tag=$(echo ${{ github.ref }} | tr '[:upper:]' '[:lower:]')
          if [[ $tag =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+.*(rc|beta|alpha).* ]]; then
            echo ::set-output name=pre-release::true
          else 
            echo ::set-output name=pre-release::false
          fi
      - name: Create Release
        id: create-release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: ${{ steps.pre-release.outputs.pre-release }}
