name: -Reusable Publish Release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: Version to publish

jobs:
  publish:
    name: Publish ${{ inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Is Pre Release ?
        id: pre_release
        if: github.event_name != 'workflow_dispatch'
        uses: heineiuo/create-changelogs@v0.2.8

      - name: Build Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: .changelog-generator.json
          ignorePreReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create-release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.version }}
          release_name: Release ${{ inputs.version }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: ${{ github.event_name != 'workflow_dispatch' && steps.pre_release.outputs.release_type == 'prerelease' }}
